### PR TITLE
fix(vllm): accept prepend kwarg in ElasticBlockPool.free_blocks

### LINKED ISSUE #438: ElasticBlockPool.free_blocks() breaks on newer vLLM: unexpected keyword argument 'prepend'
### Problem

vLLM's `BlockPool.free_blocks()` now takes a `prepend` keyword argument that kvcached's injected `ElasticBlockPool` override does not accept. On vLLM 0.23.0 engine startup dies:

```
TypeError: ElasticBlockPoolPatch.inject_elastic_block_pool.<locals>.ElasticBlockPool.free_blocks() got an unexpected keyword argument 'prepend'
```

Hit while filling the vLLM side of #425 (`google/gemma-4-12B-it`, `KVCACHED_CONTIGUOUS_LAYOUT=false`, A100, kvcached main `8aa9a04`). Observed on 0.23.0, not bisected to the vLLM version that introduced the kwarg. Separate from and earlier than the 0.24+ page-size issue in #399.

### Expected behavior

`ElasticBlockPool.free_blocks()` accepts the current vLLM signature and honors `prepend`, keeping old behavior on older vLLMs. Same shape as the SGLang allocator drift fix in #411.

I have a fix ready and will open a PR referencing this issue.

### PR DESCRIPTION
**Pull request by rishabhsinha17**
## Summary

Accept the `prepend` keyword in `ElasticBlockPool.free_blocks()` so kvcached survives the newer vLLM `BlockPool.free_blocks(ordered_blocks, prepend=...)` signature.

Fixes #438.

## Root cause

vLLM's `BlockPool.free_blocks()` grew `prepend: bool = False` (present in 0.23.0): freed blocks go to the front of vLLM's free queue for reuse priority. kvcached's injected `ElasticBlockPool` did not accept the kwarg, so engine startup on vLLM 0.23 dies during warmup:

```
TypeError: ElasticBlockPoolPatch.inject_elastic_block_pool.<locals>.ElasticBlockPool.free_blocks() got an unexpected keyword argument 'prepend'
```

## Changes

- `free_blocks()` accepts `prepend: bool = False`. The hint is intentionally unused: kvcached has no linear free queue, reuse order is governed by `KVCacheManager`'s page-affine allocation (`_pick_avail_page`), so there is nothing meaningful to prepend to. Comment in code records this.
- Older vLLMs that call without the kwarg are unaffected.
- Same drift class as the SGLang-side allocator fix in #411.

## Validation

- `tests/test_prefix_cache.py`: two new CPU-only tests, `prepend=True/False` on both the caching and caching-disabled paths; 32 passed.
- On unfixed main, `pool.free_blocks(blocks, prepend=True)` raises the TypeError above; with this patch it frees normally.
- GPU check on the #438 repro (A100, vLLM 0.23.0, `google/gemma-4-12B-it`, `KVCACHED_CONTIGUOUS_LAYOUT=false`): startup now proceeds past the block-pool TypeError. Result of the full run posted below once complete (the model may still hit later incompatibilities on 0.23; this PR scopes to the free_blocks drift).
- `ruff`, `isort`, mypy: no new findings (identical baseline to main).

### CODE REVIEW

**Comment by rishabhsinha17** [comment]
GPU verification on the #438 repro (A100, vLLM 0.23.0, `google/gemma-4-12B-it`, `KVCACHED_CONTIGUOUS_LAYOUT=false`, branch `7d7a2ae`):

Before: startup dies with the `free_blocks` TypeError.
After: no TypeError, engine starts and generates.

Output on this config is garbled (`'111.11.111...'`). (Revised 2026-08-15: I originally attributed this to degenerate vanilla-vLLM-0.23 baselines per the #425 notes; that caveat was withdrawn on #425, my harness was sending raw completion prompts to -it models, and the garbled output here has the same harness explanation.) This PR scopes to the signature drift only, which per the #425 correction is 0.23-only: the `prepend` call sites do not exist in vLLM 0.24.

**Comment by shipiyouniao** [comment]
Reviewed the vLLM 0.23 signature change and the kvcached free path. Accepting the optional argument is backward-compatible, and ignoring the ordering hint is appropriate here: kvcached does not maintain vLLM's linear free-block deque, while uncached releases return IDs to `KVCacheManager` and cached blocks remain governed by the existing eviction order. The new tests cover both values and the caching-disabled path; `tests/test_prefix_cache.py` passes locally (32 passed). No blocking issues from my side.

**Comment by rishabhsinha17** [comment]
@RixinLiu this one is ready,shipiyouniao reviewed it with no issues and it is CLEAN. It closes #438, which the #425 sequencing puts ahead of #417. The checks here ran before #403's CPU CI landed.

File: kvcached/integration/vllm/patches.py [hunk 1]
```diff
@@ -768,7 +768,13 @@ def touch(
             def free_blocks(
                 self,
                 ordered_blocks: Iterable[KVCacheBlock],
+                prepend: bool = False,
             ) -> None:
+                # vLLM >= 0.23 passes ``prepend`` to put freed blocks at the
```
Comment (jeff3071) [inline kvcached/integration/vllm/patches.py:773]: nit: prepend kwarg only set when vllm version is 0.23. 0.24 and 0.25 remove it.

**Review by jeff3071 — APPROVED** [review]
LGTM

**Comment by RixinLiu** [comment]
Thanks for the reminder. LGTM
