### ISSUE TITLE
ElasticBlockPool.free_blocks() breaks on newer vLLM: unexpected keyword argument 'prepend'

### ISSUE THREAD

**Issue by rishabhsinha17** [ovg-project/kvcached#438]
### Problem

vLLM's `BlockPool.free_blocks()` now takes a `prepend` keyword argument that kvcached's injected `ElasticBlockPool` override does not accept. On vLLM 0.23.0 engine startup dies:

```
TypeError: ElasticBlockPoolPatch.inject_elastic_block_pool.<locals>.ElasticBlockPool.free_blocks() got an unexpected keyword argument 'prepend'
```

Hit while filling the vLLM side of #425 (`google/gemma-4-12B-it`, `KVCACHED_CONTIGUOUS_LAYOUT=false`, A100, kvcached main `8aa9a04`). Observed on 0.23.0, not bisected to the vLLM version that introduced the kwarg. Separate from and earlier than the 0.24+ page-size issue in #399.

### Expected behavior

`ElasticBlockPool.free_blocks()` accepts the current vLLM signature and honors `prepend`, keeping old behavior on older vLLMs. Same shape as the SGLang allocator drift fix in #411.

I have a fix ready and will open a PR referencing this issue.
